# Eksperimen Dataset: SP 500 Analyst Rating

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1. Import Library

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

## 2. Load Dataset

In [4]:
df = pd.read_csv('/content/drive/MyDrive/BI-OJK/DICODING/sp_500_analyst_rating_and_price_target_accuracy.csv')
df.head()

,ticker,event_date,firm,from_grade,to_grade,action,price_target_action,current_price_target,prior_price_target,implied_direction,forward_return_30d_pct,forward_return_90d_pct,forward_return_180d_pct,forward_return_365d_pct,accuracy_30d,accuracy_90d,accuracy_180d,accuracy_365d
0,A,2026-04-14 21:05:30,Barclays,Overweight,Overweight,main,Lowers,140.0,150.0,1,-5.922417,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1,A,2026-04-13 08:40:20,TD Cowen,Buy,Buy,main,Lowers,147.0,157.0,1,-4.051066,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2,A,2026-04-06 16:14:02,Evercore ISI Group,Outperform,Outperform,main,Lowers,140.0,160.0,1,2.481719,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,A,2026-03-03 16:38:34,Morgan Stanley,Overweight,Overweight,main,Lowers,160.0,180.0,1,-2.769236,14.491154,NaN,NaN,0.0,1.0,NaN,NaN
4,A,2026-02-26 18:59:51,UBS,Buy,Buy,main,Lowers,165.0,180.0,1,-7.406798,-4.022223,NaN,NaN,0.0,0.0,NaN,NaN

## 3. Data Exploration & Cleaning

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71455 entries, 0 to 71454
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ticker                   71455 non-null  object
 1   event_date               71455 non-null  object
 2   firm                     71451 non-null  object
 3   from_grade               71455 non-null  object
 4   to_grade                 71455 non-null  object
 5   action                   71455 non-null  object
 6   price_target_action      61253 non-null  object
 7   current_price_target     71455 non-null  float64
 8   prior_price_target       71455 non-null  float64
 9   implied_direction        71455 non-null  int64
 10  forward_return_30d_pct   71455 non-null  float64
 11  forward_return_90d_pct   68707 non-null  float64
 12  forward_return_180d_pct  65080 non-null  float64
 13  forward_return_365d_pct  57704 non-null  float64
 14  accuracy_30d             71455 non-null  float64
 15  accuracy_90d             68707 non-null  float64
 16  accuracy_180d            65080 non-null  float64
 17  accuracy_365d            57704 non-null  float64
dtypes: float64(10), int64(1), object(7)
memory usage: 9.8+ MB

In [6]:
# Memilih fitur yang relevan
features = ['from_grade', 'to_grade', 'action', 'implied_direction']
target = 'accuracy_30d'

df = df.dropna(subset=[target] + features)

## 4. Preprocessing

In [7]:
le = LabelEncoder()
for col in ['from_grade', 'to_grade', 'action']:
    df[col] = le.fit_transform(df[col].astype(str))

In [8]:
df.head()

,ticker,event_date,firm,from_grade,to_grade,action,price_target_action,current_price_target,prior_price_target,implied_direction,forward_return_30d_pct,forward_return_90d_pct,forward_return_180d_pct,forward_return_365d_pct,accuracy_30d,accuracy_90d,accuracy_180d,accuracy_365d
0,A,2026-04-14 21:05:30,Barclays,26,23,2,Lowers,140.0,150.0,1,-5.922417,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1,A,2026-04-13 08:40:20,TD Cowen,5,4,2,Lowers,147.0,157.0,1,-4.051066,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2,A,2026-04-06 16:14:02,Evercore ISI Group,24,21,2,Lowers,140.0,160.0,1,2.481719,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,A,2026-03-03 16:38:34,Morgan Stanley,26,23,2,Lowers,160.0,180.0,1,-2.769236,14.491154,NaN,NaN,0.0,1.0,NaN,NaN
4,A,2026-02-26 18:59:51,UBS,5,4,2,Lowers,165.0,180.0,1,-7.406798,-4.022223,NaN,NaN,0.0,0.0,NaN,NaN

## 5. Save Preprocessed Data

In [9]:
import os
os.makedirs('namadataset_preprocessing', exist_ok=True)
df.to_csv('namadataset_preprocessing/sp_500_analyst_rating_and_price_target_accuracy.csv', index=False)
print('Data preprocessed saved!')

Data preprocessed saved!